server:
  port: 8082

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: seeing-api
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/seeing?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://localhost:8083 # 上传到服务端server
  redis:
    lettuce:
      max-active: 8 # 连接池最大连接数
      max-idle: 8 # 连接池最大空闲连接数
      min-idle: 0 # 连接池最小空闲连接数
      max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ym.seeing.api.domain

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
captcha:
  width: 90
  height: 90
  codeCount: 2
  thickness: 2



